[package]
name = "debounce"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.22", default-features = false, features = [
  "serde",
  "clock",
  "std",
] }
tokio = { version = "1.0", features = ["full", "tracing"] }

[dev-dependencies]
rstest = "0.16"
